name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  test-and-build-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js Environment
        uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Initialize Frontend
        run: npm ci

      - name: Format/Lint Frontend
        run: |
          npm run format
          npm run lint

      - name: Test Frontend
        run: npm run test

      - name: Build Frontend
        run: npm run build

      - name: Archive Frontend
        uses: actions/upload-artifact@v3
        with:
          name: frontend
          path: dist

  push-frontend-to-docker-hub:
    needs: test-and-build-frontend
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v3
        with:
          name: frontend
          path: dist

      - name: List Dist Contents
        run: ls -R dist

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push frontend
        uses: docker/build-push-action@v5
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: jonasfroeller/webpack-webapp:latest
          context: . # Important, else the repo context doesn't include the downloaded artifacts!!! (https://github.com/docker/build-push-action/issues/691)

  publish-frontend-to-github-pages:
    needs: test-and-build-frontend
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/download-artifact@v3
        with:
          name: frontend
          path: dist

      - name: List Dist Contents
        run: ls -R dist

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
